# Generated by Django 2.2.1 on 2019-05-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=120)),
                ('contact_no', models.CharField(max_length=20)),
                ('overview', models.CharField(max_length=400)),
                ('website', models.CharField(max_length=320)),
                ('twitter', models.CharField(max_length=120)),
                ('instagram', models.CharField(max_length=120)),
                ('facebook', models.CharField(max_length=120)),
                ('linkedIn', models.CharField(max_length=120)),
                ('image1', models.ImageField(upload_to='')),
                ('image2', models.ImageField(upload_to='')),
            ],
        ),
    ]
