# Generated by Django 2.2.1 on 2019-05-16 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Profiles',
        ),
    ]
