# Generated by Django 2.2.1 on 2019-05-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0002_auto_20190516_0607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='Profile',
        ),
    ]
