# Generated by Django 2.2.1 on 2019-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(max_length=120)),
                ('service1', models.CharField(max_length=120)),
                ('service2', models.CharField(max_length=120)),
                ('service3', models.CharField(max_length=120)),
            ],
        ),
    ]
