# Generated by Django 2.2.1 on 2019-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('Description', models.TextField()),
                ('project_link', models.CharField(max_length=120)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
    ]
