# Generated by Django 2.2.1 on 2019-05-19 18:27

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.upload_location),
        ),
    ]
