# Generated by Django 2.2.1 on 2019-05-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190519_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='niche',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
